set(CMAKE_C_FLAGS -m32)
set(CMAKE_CXX_FLAGS -m32)
set(CMAKE_SHARED_LINKER_FLAGS -m32)
set(CMAKE_STATIC_LINKER_FLAGS -m32)
set(CMAKE_EXE_LINKER_FLAGS -m32)

set(OPENSSL_INCLUDE_DIR /usr/include/i386-linux-gnu)
set(OPENSSL_ROOT_DIR "/usr/lib/i386-linux-gnu" CACHE STRING "" FORCE)