set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_C_FLAGS -m32)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_CXX_FLAGS -m32)

set(CMAKE_FIND_ROOT_PATH /usr/lib/i386-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(OPENSSL_INCLUDE_DIR /usr/include/i386-linux-gnu)

find_library(OPENSSL_SSL_LIBRARY NAMES ssl ssleay32 ssleay32MD NAMES_PER_DIR HINTS /usr/lib/i386-linux-gnu PATH_SUFFIXES lib)
find_library(OPENSSL_CRYPTO_LIBRARY NAMES crypto NAMES_PER_DIR HINTS /usr/lib/i386-linux-gnu PATH_SUFFIXES lib)

set(OPENSSL_LIBRARIES ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})